import { Component } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.html',
})
export class About {
  protected readonly skills = [
    'Firebase',
    'API REST',
    'TypeScript',
    'AngularJS',
    'CSS',
    'HTML5',
    'JavaScript',
    'Node.js',
    'Produtos Databricks',
    'NoSQL',
    'Google Data Studio',
    'Metabase',
    'Minio',
    'Amazon Redshift',
    'Amazon EC2',
    'Amazon S3',
    'ETL e ELT',
    'PostgreSQL',
    'Amazon Web Services',
    'Google Cloud Platform (GCP)',
    'Linux',
    'Desenvolvimento orientado a testes',
    'Delphi 2010',
    'Princípios SOLID',
    'Docker',
    'WSL2',
    'Delphi',
    'MySQL',
    'Scrum',
    'Python',
    'VCL Forms',
    'Intraweb',
    'dbExpress',
    'Extract, Transform, Load (ETL)',
    'SQL server',
    'Git',
    'Mobile',
    'Firedac',
    'Rad Studio',
    'Delphi Tokio',
    'SQLite',
    'Vendas',
    'Sales force',
    'App',
    'Visual Basic',
    'Práticas de engenharia de software',
    'Banco de Dados',
    'Cálculo',
    'Ética',
    'Linguagem Assembly',
    'C (linguagem de programação)',
    'Microcontroladores',
    'CLP (Controlador lógico programável)',
    'datasnap',
    'Teamwork',
    'Criatividade',
    'SQL',
    'Transact-SQL (T-SQL)',
    'PL/SQL',
    'ERP Implementations',
    'Visual Studio Code',
    'SQL Tuning',
    'pytest',
    'Data Migration',
    'Kotlin',
    'Selenium WebDriver',
    'Sourcetree',
    'Android',
    'C#',
    'ZPL',
    'Microsoft SQL Server',
    'Desenvolvimento Android',
    'Android Studio',
    'Java',
    'GitHub',
    'Microsoft Excel',
    'Jenkins',
    'Software Development',
    'PL SQL',
    'Documentação de software',
    'Prompt Engineering',
    'MongoDB',
    'Databases',
    'Midjourney',
    'Analista de Sistemas',
    'Borland Delphi',
    'Excel',
    'relatórios',
    'Auxilio ao suporte',
    'JEDI',
    'GitLab',
    'Oracle',
    'Microsoft Project',
    'Bitbucket',
    'Planejamento de projetos',
    'ERP',
    'Suporte',
    'JIRA',
    'OTRS',
  ];
}
